{{- if .Values.web.enabled }}
{{- if .Values.web.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.applicationName }}-web-ingress
  labels:
    app: {{ .Values.applicationName }}
    component: web
    chart: {{ template "common.chartName" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    revision: "{{ .Release.Revision }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
spec:
{{- if .Values.web.ingress.tlsEnabled }}
  tls:
  - hosts:
    - {{ .Values.host.prefix }}{{ .Values.host.name }}.{{ .Values.host.domain }}
    secretName: {{ .Values.applicationName }}-tls
{{- end }}
  backend:
    serviceName: nginx
    servicePort: 80
  rules:
  - host: {{ .Values.host.prefix }}{{ .Values.host.name }}.{{ .Values.host.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.applicationName }}-web-service
          servicePort: 80
{{- end }}
{{- end }}
