apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.applicationName }}-azure-secrets
  labels:
    app: {{ .Values.applicationName }}
    component: web
    chart: {{ template "common.chartName" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    revision: "{{ .Release.Revision }}"
type: Opaque
data:
  client-secret: {{ default "MISSING" .Values.azure.clientSecret | b64enc | quote }}
